add submit button component as wrapper to Button with states
ArgenSource/freezados-barf-webapp pull request #29
Opened 2023-12-29 21:42 UTC by SantiagoJavierRubio

Le agrego el submit button con la idea de que se represente medianamente el estado de las mutations ahi... principalmente para manejar respuestas lentas y dar feedback al usuario

2024-01-01 16:02 UTC, RodriCabrera requested changes

2024-01-01 16:02 UTC, RodriCabrera commented on src/features/common/components/Buttons/SubmitButton.tsx
> +  loadingStyle: "w-2/3 m-auto",
el `w-2/3` hace que se achique el boton base que tiene un `w-full`.
Me genera un movimiento en el form, al momento del submit, cuando el boton se achica.
que opinas de borrar el `w-2/3`? como para que el boton mantenga el tamanio?

![image](https://github.com/ArgenSource/freezados-barf-webapp/assets/65794827/dd2335d9-2637-45bc-bf27-65816e1f6a46)


![image](https://github.com/ArgenSource/freezados-barf-webapp/assets/65794827/c7917f84-65c3-4a57-8b41-387868647b55)

2024-01-02 12:40 UTC, SantiagoJavierRubio commented on src/features/common/components/Buttons/SubmitButton.tsx
> +  loadingStyle: "w-2/3 m-auto",
Si, no me acuerdo por que lo puse

2024-01-02 13:08 UTC, RodriCabrera approved these changes

2024-01-02 13:09 UTC, merged